/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package humanmachine;

import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferStrategy;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.ImageIcon;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.Timer;
/**
 *
 * @author nele
 */
public class GameFrame extends JFrame {
    String text_help;
    Player human = new Player (true,0);
    Player machine = new Player (false,0);
    Game game;// = new Game();
    int chat_index=0;
    boolean wait_for_respond=false;
    
    /**
     *
     */
    public GameFrame() {
        initComponents();
        
        Timer timer=new Timer(2000,new ActionListener(){
            public void actionPerformed(ActionEvent e)
            {
                //if ((game.chats[0]).length()>0) {
                if (!wait_for_respond) {
                        if ((game.chats[chat_index])!=null) {
                        text_help=game.chats[chat_index];
                        text_help="\n".concat(text_help);
                        text_help=text_help.concat("\n");
                        text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
                        chat_area.append(text_help);

                        if ((game.chat_paths[chat_index]!=null)) {// & (game.chat_paths[chat_index].length()>0)) {
                            System.out.println("chatpath "+chat_index+" "+game.chat_paths[chat_index]);
                            image_label_chat.setIcon(new ImageIcon(getClass().getResource(game.chat_paths[chat_index])));

                        }
                        chat_index++;
                        wait_for_respond=true;
                        System.out.println("chat_index "+chat_index);
                    }
                }
            }
        });
        timer.start();
        //timer.stop()
    }

    /**
     *
     * @return
     */
    @Override
    public BufferStrategy getBufferStrategy() {
        return super.getBufferStrategy(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     *
     * @return
     */
    public JPanel getImage_panel() {
        return image_panel;
    }
    
    
    private static void initAndShowGUI()
    {
        final JFXPanel fxPanel = new JFXPanel();
        //frame.add(fxPanel);
        
        //frame.setVisible(true);
        Platform.runLater(new Runnable()
        {
            @Override
            public void run()
            {
                initFX(fxPanel);
            }
        });
    }
    private static void initFX(JFXPanel fxPanel)
    {
        // This method is invoked on JavaFX thread
        //final Scene scene = TextIntegrationSceneCreator.createTextScene();
        //fxPanel.setScene(scene);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_panel = new javax.swing.JPanel();
        image_label = new javax.swing.JLabel();
        label_points_machine = new javax.swing.JLabel();
        label_points_human = new javax.swing.JLabel();
        points_human_display = new javax.swing.JLabel();
        points_machine_display = new javax.swing.JLabel();
        confirm_button = new javax.swing.JButton();
        info_button = new javax.swing.JButton();
        start_button = new javax.swing.JButton();
        human_answer_label = new javax.swing.JLabel();
        machine_answer_label1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat_area = new javax.swing.JTextArea();
        chat_message_tf = new javax.swing.JTextField();
        confirm_chat_button = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        answer_machine_ta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        answer_human_ta = new javax.swing.JTextArea();
        next_button = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        question_ta = new javax.swing.JTextArea();
        human_answer_label1 = new javax.swing.JLabel();
        image_label_chat = new javax.swing.JLabel();
        machine_answer_label2 = new javax.swing.JLabel();
        label_points_machine1 = new javax.swing.JLabel();
        label_points_human1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout image_panelLayout = new javax.swing.GroupLayout(image_panel);
        image_panel.setLayout(image_panelLayout);
        image_panelLayout.setHorizontalGroup(
            image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_panelLayout.createSequentialGroup()
                .addComponent(image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        image_panelLayout.setVerticalGroup(
            image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_panelLayout.createSequentialGroup()
                .addComponent(image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        label_points_machine.setText("Score non-");

        label_points_human.setText("Score human");

        points_human_display.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        points_human_display.setText("0");

        points_machine_display.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        points_machine_display.setText("0");

        confirm_button.setText("Confirm");
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });

        info_button.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        info_button.setLabel("i");
        info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_buttonActionPerformed(evt);
            }
        });

        start_button.setText("Start Game");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        human_answer_label.setText("Your answer:");

        machine_answer_label1.setText("Non-human");

        chat_area.setEditable(false);
        chat_area.setColumns(20);
        chat_area.setRows(5);
        jScrollPane1.setViewportView(chat_area);

        chat_message_tf.setText("Talk with me");
        chat_message_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_message_tfActionPerformed(evt);
            }
        });

        confirm_chat_button.setText("Send");
        confirm_chat_button.setToolTipText("");
        confirm_chat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_chat_buttonActionPerformed(evt);
            }
        });

        answer_machine_ta.setEditable(false);
        answer_machine_ta.setColumns(20);
        answer_machine_ta.setRows(5);
        jScrollPane2.setViewportView(answer_machine_ta);

        answer_human_ta.setColumns(20);
        answer_human_ta.setRows(5);
        jScrollPane3.setViewportView(answer_human_ta);

        next_button.setText("Next");
        next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_buttonActionPerformed(evt);
            }
        });

        question_ta.setEditable(false);
        question_ta.setBackground(new java.awt.Color(204, 204, 204));
        question_ta.setColumns(20);
        question_ta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        question_ta.setLineWrap(true);
        question_ta.setRows(5);
        question_ta.setWrapStyleWord(true);
        question_ta.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        question_ta.setEnabled(false);
        jScrollPane4.setViewportView(question_ta);

        human_answer_label1.setText("Question:");

        machine_answer_label2.setText("player:");

        label_points_machine1.setText("human player");

        label_points_human1.setText("player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_points_human, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_points_human1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(points_human_display, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_points_machine, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_points_machine1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(points_machine_display, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addComponent(image_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(chat_message_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirm_chat_button))
                            .addComponent(image_label_chat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(human_answer_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(next_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(info_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(machine_answer_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(machine_answer_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(human_answer_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirm_button))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(start_button))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_points_machine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(points_machine_display)
                                .addComponent(label_points_machine1)
                                .addComponent(points_human_display, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_points_human)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_points_human1)))))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addComponent(start_button)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(human_answer_label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(human_answer_label)
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(machine_answer_label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(machine_answer_label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chat_message_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirm_chat_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(image_label_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        //answer_machine_ta.setFont(new Font("Serif", Font.ITALIC, 16));
        answer_machine_ta.setLineWrap(true);
        answer_machine_ta.setWrapStyleWord(true);
        text_help="";
        text_help=game.getCurrentAnswerMachine();
        text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
        
        answer_machine_ta.setText(text_help);
        game.setState(2);
        
        //How to get a point
        if (game.getCurrentAnswerMachine().equals(game.getCurrentCorrectAnswer())) {machine.addPoints(1);}
        if (answer_human_ta.getText().equals(game.getCurrentCorrectAnswer()) & !answer_human_ta.getText().equals("")) {human.addPoints(1);}
        
        
        points_human_display.setText(Integer.toString(human.points));
        points_machine_display.setText(Integer.toString(machine.points));
        
    }//GEN-LAST:event_confirm_buttonActionPerformed

    private void info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_buttonActionPerformed
        text_help=game.getIDescription();
        if (text_help!=null & !text_help.equals("")){
            text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
            JOptionPane.showMessageDialog(getImage_panel(), text_help, "title" ,INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(getImage_panel(), "You are on your own!", "title" ,INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_info_buttonActionPerformed

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        // TODO add your handling code here:
        game=new Game();
        game.readQuestions();
        game.nextRound();
        chat_index=0;
        wait_for_respond=false;
        
        chat_area.setLineWrap(true);
        chat_area.setWrapStyleWord(true);
        
        text_help=game.getCurrentQuestion();
        text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
        question_ta.setText(text_help);   
        
        question_ta.append("\n\n");   
        text_help=game.getCurrentQDescription();
        if (text_help!= null){
            text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
            question_ta.append(text_help); 
        }
        
        answer_machine_ta.setText("");                                           
        answer_human_ta.setText("");
        if (game.getCurrentQPath()!=null) {
            System.out.println("path "+game.getCurrentQPath());
            image_label.setIcon(new ImageIcon(getClass().getResource(game.getCurrentQPath())));
        }
        //Image image = new Image("rohrschach01.jpg");
        //image_panel.add(image, this);
        //image_label.setIcon(icon);
        //image_label.setIcon(new ImageIcon("rohrschach01.jpg"));
        //System.out.println("ok");
        //new ImageIcon("rohrschach01.jpg")
    }//GEN-LAST:event_start_buttonActionPerformed

    private void confirm_chat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_chat_buttonActionPerformed
        // TODO add your handling code here:
        //chat_area.setFont(new Font("Serif", Font.ITALIC, 16));
        //chat_area.setLineWrap(true);
        //chat_area.setWrapStyleWord(true);
        text_help=chat_message_tf.getText();
        text_help="ME: ".concat(text_help);
        text_help=text_help.concat("\n");
        text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
        chat_area.append(text_help);
        wait_for_respond=false;
        
    }//GEN-LAST:event_confirm_chat_buttonActionPerformed

    private void next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_buttonActionPerformed
        // TODO add your handling code here:
        game.nextRound();
        //System.out.println(game.getRound());
        if ((game.getRound())>=game.getMaxRound()) {
            text_help="\nEND OF GAME!\n";
            text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
            chat_area.append(text_help);
        } else {
            //question_ta.setFont(new Font("Serif", Font.ITALIC, 16));
            //question_ta.setLineWrap(true);
            //question_ta.setWrapStyleWord(true);
            text_help=game.getCurrentQuestion();
            text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
            question_ta.setText(text_help);   

            question_ta.append("\n\n");   
            text_help=game.getCurrentQDescription();
            if (text_help!= null){
                text_help = text_help.replaceAll("\\\\n", System.getProperty("line.separator"));
                question_ta.append(text_help); 
            }
            
            answer_machine_ta.setText("");                                           
            answer_human_ta.setText("");
            System.out.println("XX i path:"+game.getCurrentQPath());
            image_label.setIcon(new ImageIcon(getClass().getResource(game.getCurrentQPath())));
            
        }
    }//GEN-LAST:event_next_buttonActionPerformed

    private void chat_message_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_message_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chat_message_tfActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answer_human_ta;
    private javax.swing.JTextArea answer_machine_ta;
    private javax.swing.JTextArea chat_area;
    private javax.swing.JTextField chat_message_tf;
    private javax.swing.JButton confirm_button;
    private javax.swing.JToggleButton confirm_chat_button;
    private javax.swing.JLabel human_answer_label;
    private javax.swing.JLabel human_answer_label1;
    private javax.swing.JLabel image_label;
    private javax.swing.JLabel image_label_chat;
    private javax.swing.JPanel image_panel;
    private javax.swing.JButton info_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_points_human;
    private javax.swing.JLabel label_points_human1;
    private javax.swing.JLabel label_points_machine;
    private javax.swing.JLabel label_points_machine1;
    private javax.swing.JLabel machine_answer_label1;
    private javax.swing.JLabel machine_answer_label2;
    private javax.swing.JButton next_button;
    private javax.swing.JLabel points_human_display;
    private javax.swing.JLabel points_machine_display;
    private javax.swing.JTextArea question_ta;
    private javax.swing.JButton start_button;
    // End of variables declaration//GEN-END:variables
}
